---
extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - prettier
  - react-hooks
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  react/prop-types: 0
  no-underscore-dangle: 0
  jsx-a11y/label-has-for: 0
  import/imports-first:
    - error
    - absolute-first
  import/newline-after-import: error
  no-param-reassign:
    - 1
    - ignorePropertyModificationsFor:
        - draft # disable when param starts with draft (e.g. for immer)
globals:
  window: true
  document: true
  localStorage: true
  FormData: true
  FileReader: true
  Blob: true
  navigator: true
parser: babel-eslint